---

- name: Create Project Directory
  file:
    path: "{{ project_dir }}/{{ item }}"
    state: directory
    mode: 0755
  loop:
  - nginx/ssl
  - data
  - dist

- name: Copy DockerFile to server
  copy:
    src: "nodejsProject/{{ item }}"
    dest: "{{ project_dir }}/"
    mode: 0755
  loop:
  - Dockerfile

- name: Copy javascript Files to server
  copy:
    src: "nodejsProject/{{ item }}"
    dest: "{{ project_dir }}/dist"
    mode: 0755
  loop:
  - dist/index.js
  - dist/package.json